apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mcServer.pvc.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: "Prune=false,Delete=false"
    helm.sh/resource-policy: keep
  labels:
    app: mc-server
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-static
  resources:
    requests:
      storage: {{ .Values.mcServer.pvc.size }}
