version: '3.8'

services:
  discordbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discordbot
    environment:
      - DEPLOYMENT=local
      - DOCKER_COMPOSE_SLUG=mcserver-modded-1

      - DISCORD_API_TOKEN=your_discord_api_token
      - DISCORD_DEBUG_GUILD_IDS=

      - SERVER_ADDRESS=dewcraft.duckdns.org
      - SERVER_PORT_JAVA=25565
      - SERVER_PORT_BEDROCK=19132
      - SERVER_MAP_PORT=8192
      - SERVER_THUMBNAIL_URL=https://img.icons8.com/plasticine/344/minecraft-grass-cube--v1.png
    restart: unless-stopped
    # Local deployment launches the mc server via docker compose on the host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/user1/compose.yaml:/data/compose.yaml