FROM python:3.13-slim

RUN python -m ensurepip --upgrade
COPY requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*

ENV DEPLOYMENT=kubernetes

COPY bot /app/bot
COPY container-init.sh /app/container-init.sh

WORKDIR /app
RUN chmod +x ./container-init.sh
CMD ["./container-init.sh"]
